use_frameworks!

platform :ios, '10.0'

target 'CommonNetwork_Example' do
  pod 'CommonNetwork', :path => '../'

  target 'CommonNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
